### ISSUE TITLE
Assertion failed error on login

### ISSUE THREAD

**Issue by ptpofficialxd** [giorgi-o/SkinPeek#121]
Hi, everytime I use /login the error occurs as this below

Assertion failed: Auth status code is 502! {
  statusCode: 502,
  headers: {
    server: 'cloudflare',
    date: 'Sun, 21 Jul 2024 00:47:02 GMT',
    'content-type': 'text/html',
    'content-length': '155',
    connection: 'close',
    'cf-ray': '8a672d69cf867992-BKK'
  },
  body: '<html>\r\n' +
    '<head><title>502 Bad Gateway</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>502 Bad Gateway</h1></center>\r\n' +
    '<hr><center>cloudflare</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}

**Comment by BajekekButLost** [comment]
Same issue happening to me :(

**Comment by ConnorDoesDev** [comment]
Old auth flow is deprecated afaik
we gotta use captcha solvers now

**Comment by Madfish5415** [comment]
Maybe with a different user-agent

**Comment by xFanexx** [comment]
Not working for me either.

**Comment by tacotyen** [comment]
same problem here. also, how do you get a HDEV token? is it the same as a HDEV key? is it even required ☹️

**Comment by ArishioTing** [comment]
i got this issue too. So frustrating

**Comment by CrazygreenTW** [comment]
me too:
myid#0 used /login
Assertion failed: Auth status code is 502! {
  statusCode: 502,
  headers: {
    server: 'cloudflare',
    date: 'Thu, 26 Sep 2024 15:43:38 GMT',
    'content-type': 'text/html',
    'content-length': '155',
    connection: 'close',
    'cf-ray': '8c945ee77895f244-KHH'
  },
  body: '<html>\r\n' +
    '<head><title>502 Bad Gateway</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>502 Bad Gateway</h1></center>\r\n' +
    '<hr><center>cloudflare</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
 Riot didn't return any cookies during the auth request! Cloudflare might have something to do with it...
 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at redeemUsernamePassword (file:///C:/Users/User/Desktop/valbot/valorant/auth.js:166:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async queueUsernamePasswordLogin (file:///C:/Users/User/Desktop/valbot/valorant/authQueue.js:33:38)
    at async loginUsernamePassword (file:///C:/Users/User/Desktop/valbot/discord/authManager.js:40:17)
    at async Client.<anonymous> (file:///C:/Users/User/Desktop/valbot/discord/bot.js:940:21)
