### ISSUE TITLE
Not working shop

### ISSUE THREAD

**Issue by zlyyy0** [giorgi-o/SkinPeek#126]
Fetching shop for zlyyy#salam...
Assertion failed: Valorant skins offers code is 405! {
  statusCode: 405,
  headers: {
    date: 'Tue, 24 Sep 2024 17:38:41 GMT',
    'content-type': 'text/plain; charset=utf-8',
    'content-length': '19',
    connection: 'keep-alive',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'cf-cache-status': 'DYNAMIC',
    server: 'cloudflare',
    'cf-ray': '8c848cb2dae3c077-WAW'
  },
  body: 'Method Not Allowed\n'
}
 SyntaxError: Unexpected token 'M', "Method Not Allowed
" is not valid JSON
    at JSON.parse (<anonymous>)
    at getShop (file:///C:/Users/Kacper/Desktop/SkinPeek-master/valorant/shop.js:38:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getOffers (file:///C:/Users/Kacper/Desktop/SkinPeek-master/valorant/shop.js:69:18)
    at async fetchShop (file:///C:/Users/Kacper/Desktop/SkinPeek-master/valorant/shopManager.js:15:16)
    at async Client.<anonymous> (file:///C:/Users/Kacper/Desktop/SkinPeek-master/discord/bot.js:672:37)

**Comment by ConnorDoesDev** [comment]
Riot has changed the public endpoint as far as I know. Not sure tho. 
Just wait till the public documentation updates if you dont wanna check for the new one yourself
