### ISSUE TITLE
Everyday always makes me login to the bot

### ISSUE THREAD

**Issue by sugoides** [giorgi-o/SkinPeek#20]
I've been using this bot now for about a week, and something that I noticed is that, it makes me login to the bot everyday. why is that?

**Comment by sugoides** [comment]
btw nice bot

**Comment by blongnh** [comment]
try to use `storePasswords: true`. you're getting logged out because the bot aren't logging in again automatically for you. there's no other solution that i know of, but let's wait to see if Giorgio has an idea.

**Comment by sugoides** [comment]
Niceeee, thanks, I'll let you know if it works

**Comment by warriorzz** [comment]
I wouldn't use storePasswords, rather use /cookies and tick the box 'remeber this device' (I don't know exactly what it is called) when logging in with your browser, this works fine for me, haven't logged in in a while.

**Comment by blongnh** [comment]
> I wouldn't use storePasswords, rather use /cookies and tick the box 'remeber this device' (I don't know exactly what it is called) when logging in with your browser, this works fine for me, haven't logged in in a while.

Yeah this is the safer way since passwords are stored in plain text. There has not been an option to do that on web as far as I know. The "remember this app for 30 days" is only on the Rito Client. Correct me if I am wrong though!

**Comment by warriorzz** [comment]
My bad, it's 'Stay signed in'.

**Comment by blongnh** [comment]
In 4aac4fe5614033919a502626b0e0ad09a3222e20, Giorgio enabled that option. I think we shouldn't be logged out anymore.

@sugoides You should update your bot!

**Comment by sugoides** [comment]
> In [4aac4fe](https://github.com/giorgi-o/SkinPeek/commit/4aac4fe5614033919a502626b0e0ad09a3222e20), Giorgio enabled that option. I think we shouldn't be logged out anymore.
> 
> @sugoides You should update your bot!
so even `storePassword=false` will it remember the login?

**Comment by giorgi-o** [comment]
Yup!

**Comment by sugoides** [comment]
new commands `!message !status !forcealerts` doesn't work, is it something with ownerId in config, will I put my discord tag there?

**Comment by blongnh** [comment]
> new commands `!message !status !forcealerts` doesn't work, is it something to do with ownerId in config, will I put my discord tag there?

You have to put your user ID in there, not your discord tag.

**Comment by sugoides** [comment]
> new commands `!message !status !forcealerts` doesn't work, is it something to do with ownerId in config, will I put my discord tag there?

got it now

**Comment by sugoides** [comment]
Hello, somewhat unrelated, but I host my bot in heroku, and hosting a bot in heroku have a cycling period that happens once a day, when this happens it restarts my bot, and all the logins and alert will be gone. any suggestions in interacting with this problem?

**Comment by PaizTralala** [comment]
> Hello, somewhat unrelated, but I host my bot in heroku, and hosting a bot in heroku have a cycling period that happens once a day, when this happens it restarts my bot, and all the logins and alert will be gone. any suggestions in interacting with this problem?

Hello, first time appearing on this issue and would like to help 😊, afaik, Heroku is not the best way to host your Discord bot though, because Heroku will restart once a day, and for that.. I think you can use a VPS (Virtual Private Server), because VPS doesn't do that, if I'm wrong, I'm sorry. Maybe the other can suggest a better hosting? (Sorry if it's unrelated to the issue 😅)

**Comment by sugoides** [comment]
> > Hello, somewhat unrelated, but I host my bot in heroku, and hosting a bot in heroku have a cycling period that happens once a day, when this happens it restarts my bot, and all the logins and alert will be gone. any suggestions in interacting with this problem?
> 
> Hello, first time appearing on this issue and would like to help blush, afaik, Heroku is not the best way to host your Discord bot though, because Heroku will restart once a day, and for that.. I think you can use a VPS (Virtual Private Server), because VPS doesn't do that, if I'm wrong, I'm sorry. Maybe the other can suggest a better hosting? (Sorry if it's unrelated to the issue sweat_smile)

i've use `render.com` I will be monitoring if it is good for a 24/7 runtine

**Comment by warriorzz** [comment]
> Hello, somewhat unrelated, but I host my bot in heroku, and hosting a bot in heroku have a cycling period that happens once a day, when this happens it restarts my bot, and all the logins and alert will be gone. any suggestions in interacting with this problem?

Although I haven't used Heroku at any time, you should be able to save files (like your `config.json`), just add all files in `/path/to/your/bot/data` (`alters.json`, `skins.json`, `users.json`), this will save all necessary data.

**Comment by sugoides** [comment]
> > Hello, somewhat unrelated, but I host my bot in heroku, and hosting a bot in heroku have a cycling period that happens once a day, when this happens it restarts my bot, and all the logins and alert will be gone. any suggestions in interacting with this problem?
> 
> Although I haven't used Heroku at any time, you should be able to save files (like your `config.json`), just add all files in `/path/to/your/bot/data` (`alters.json`, `skins.json`, `users.json`), this will save all necessary data.

my prob is when I deploy the bot in heroku, the bot doesn't write on those json files although if I run the bot locally it stores data on those .json

**Comment by sugoides** [comment]
```There was a problem while trying to handle an error!
Here's the original error:
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5)
    at async Client.<anonymous> (file:///D:/Discord/bot/GameRoles/GameRole/discord/bot.js:493:46) {
  method: 'post',
  path: '/interactions/958414778886418462/aW50ZXJhY3Rpb246OTU4NDE0Nzc4ODg2NDE4NDYyOjFGRG1UeUpqS25UQ05xWUtuejlicDNYcFQ0ZWdGOHk1Qk1NZjJoOVdrMnIwalJ4M3NPWElhTkI2Z2hGeVpDeEY0SHliV0VWa3ZKbGFZcERoSG5MY3ZkeHVBU3kycGtPYTcxY2NETDdlY09CbzRPbEczRG5PZGtLekFEVEtlN0NU/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}

And here's the error while trying to handle it:
DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5)
    at async handleError (file:///D:/Discord/bot/GameRoles/GameRole/discord/bot.js:933:14)
    at async Client.<anonymous> (file:///D:/Discord/bot/GameRoles/GameRole/discord/bot.js:819:13) {
  method: 'post',
  path: '/interactions/958414778886418462/aW50ZXJhY3Rpb246OTU4NDE0Nzc4ODg2NDE4NDYyOjFGRG1UeUpqS25UQ05xWUtuejlicDNYcFQ0ZWdGOHk1Qk1NZjJoOVdrMnIwalJ4M3NPWElhTkI2Z2hGeVpDeEY0SHliV0VWa3ZKbGFZcERoSG5MY3ZkeHVBU3kycGtPYTcxY2NETDdlY09CbzRPbEczRG5PZGtLekFEVEtlN0NU/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
sugoi#8552 used /login
There was a problem while trying to handle an error!
Here's the original error:
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.deferReply (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:57:5)
    at async defer (file:///D:/Discord/bot/GameRoles/GameRole/misc/util.js:159:5)
    at async Client.<anonymous> (file:///D:/Discord/bot/GameRoles/GameRole/discord/bot.js:672:21) {
  method: 'post',
  path: '/interactions/958414853213667388/aW50ZXJhY3Rpb246OTU4NDE0ODUzMjEzNjY3Mzg4OmFTbU9UN09lWktlMjVFeUF3RDM4T2ZnM21ZOTNXNXJOZG1EQUFrSG9EdzMyMkxISnhlVjZNSkNwZVVyeHdWSnVMN0ZuVVlNdzlrcHkxbUxINWhQdWx6STJLRlRhNWJObzFKaWdCR0x3bmFmNURtcW5TaUhnYlkzZlpWRXZTU1lG/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 5, data: [Object] }, files: [] }
}

And here's the error while trying to handle it:
DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (D:\Discord\bot\GameRoles\GameRole\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5)
    at async handleError (file:///D:/Discord/bot/GameRoles/GameRole/discord/bot.js:933:14)
    at async Client.<anonymous> (file:///D:/Discord/bot/GameRoles/GameRole/discord/bot.js:819:13) {
  method: 'post',
  path: '/interactions/958414853213667388/aW50ZXJhY3Rpb246OTU4NDE0ODUzMjEzNjY3Mzg4OmFTbU9UN09lWktlMjVFeUF3RDM4T2ZnM21ZOTNXNXJOZG1EQUFrSG9EdzMyMkxISnhlVjZNSkNwZVVyeHdWSnVMN0ZuVVlNdzlrcHkxbUxINWhQdWx6STJLRlRhNWJObzFKaWdCR0x3bmFmNURtcW5TaUhnYlkzZlpWRXZTU1lG/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}```

my bad, i now got this error when running locally

**Comment by warriorzz** [comment]
> > > Hello, somewhat unrelated, but I host my bot in heroku, and hosting a bot in heroku have a cycling period that happens once a day, when this happens it restarts my bot, and all the logins and alert will be gone. any suggestions in interacting with this problem?
> > 
> > 
> > Although I haven't used Heroku at any time, you should be able to save files (like your `config.json`), just add all files in `/path/to/your/bot/data` (`alters.json`, `skins.json`, `users.json`), this will save all necessary data.
> 
> my prob is when I deploy the bot in heroku, the bot doesn't write on those json files although if I run the bot locally it stores data on those .json

Are those files created or did you create them manually?

**Comment by giorgi-o** [comment]
Heroku's filesystem is ephemeral, meaning any files it creates get deleted when the server restarts. It's not a good fit for the bot unfortunately.
https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

**Comment by sugoides** [comment]
> Heroku's filesystem is ephemeral, meaning any files it creates get deleted when the server restarts. It's not a good fit for the bot unfortunately. https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

I was able to have a firebase cloud storage to store these json files, but haveing a hard time making the bot communicate to read and write to json files in the cloud storage

**Comment by sugoides** [comment]
I found the documentation for saving data in the cloud storage
https://firebase.google.com/docs/database/rest/save-data but having hard time using curl in node

**Comment by sugoides** [comment]
> I found the documentation for saving data in the cloud storage https://firebase.google.com/docs/database/rest/save-data but having hard time using curl in node

UPDATE: successfully used firebase realtime database for saving of data and get data from firebase whenever the bot starts
