### ISSUE TITLE
Queue Issues -- TypeError: Cannot read properties of undefined (reading 'result')

### ISSUE THREAD

**Issue by blongnh** [giorgi-o/SkinPeek#21]
I am pretty sure this has something to do with queue. It's only triggered when an user is put into queue.
```
TypeError: Cannot read properties of undefined (reading 'result')
    at getQueueItemStatus (file:///C:/aaaa/SkinPeek-master/valorant/authQueue.js:69:43)
    at Client.<anonymous> (file:///C:/aaaa/SkinPeek-master/discord/bot.js:663:45)
TypeError: Cannot read properties of undefined (reading 'result')
    at getQueueItemStatus (file:///C:/aaaa/SkinPeek-master/valorant/authQueue.js:69:43)
    at Client.<anonymous> (file:///C:/aaaa/SkinPeek-master/discord/bot.js:629:45)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:497:9)
TypeError: Cannot read properties of undefined (reading 'result')
    at getQueueItemStatus (file:///C:/aaaa/SkinPeek-master/valorant/authQueue.js:69:43)
    at Client.<anonymous> (file:///C:/aaaa/SkinPeek-master/discord/bot.js:629:45)
Error: getaddrinfo ENOTFOUND pd.undefined.a.pvp.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'pd.undefined.a.pvp.net'
```
Looks like the bot just didn't catch the user's region...

**Comment by giorgi-o** [comment]
Hmm, weird. My guess is that the user hasn't launched Valorant on their account yet, only League/Wild Rift.
The only way to know would be to ask the user though.

**Comment by blongnh** [comment]
> Hmm, weird. My guess is that the user hasn't launched Valorant on their account yet, only League/Wild Rift. The only way to know would be to ask the user though.

I'll see if someone reports this back. `Cannot read properties of undefined` happens once every few interactions tho.

For `Error: getaddrinfo ENOTFOUND pd.undefined.a.pvp.net`, it has only happened 10 times in a lifetime. I think there was indeed someone who logged into the shop checking bot... without a VALORANT account.

![](https://i.imgur.com/EMKOZkt.png)
